import Cr1 from "../images/01.jpg";
const CardDataset = [
  {
    id: 1,
    cardImg: Cr1,
    tagsName: "Verified",
    sale: "For sale",
    cottage: "Cottage | 120 sq.m",
    address: " 42 Broadway New York, NY 10004",
    price: "184, 000",
    icons1: "fa fa-bed",
    icons2: "fa fa-bath",
    icons3: "fa fa-car",
  },
  {
    id: 2,
    cardImg: Cr1,
    tagsName: "Verified",
    sale: "For sale",
    cottage: "Cottage | 120 sq.m",
    address: " 42 Broadway New York, NY 10004",
    price: "184, 000",
    icons1: "fa fa-bed",
    icons2: "fa fa-bath",
    icons3: "fa fa-car",
  },
  {
    id: 3,
    cardImg: Cr1,
    tagsName: "Verified",
    sale: "For sale",
    cottage: "Cottage | 120 sq.m",
    address: " 42 Broadway New York, NY 10004",
    price: "184, 000",
    icons1: "fa fa-bed",
    icons2: "fa fa-bath",
    icons3: "fa fa-car",
  },
  {
    id: 4,
    cardImg: Cr1,
    tagsName: "Verified",
    sale: "For sale",
    cottage: "Cottage | 120 sq.m",
    address: " 42 Broadway New York, NY 10004",
    price: "184, 000",
    icons1: "fa fa-bed",
    icons2: "fa fa-bath",
    icons3: "fa fa-car",
  },
];
export default CardDataset;
